ARG ELIXIR_VERSION=1.18.4
ARG DEBIAN_VERSION=bookworm-slim

FROM elixir:${ELIXIR_VERSION}-slim

ENV LANG="en_US.UTF-8" \
    LANGUAGE="en_US:en" \
    LC_ALL="en_US.UTF-8"


RUN apt-get update -y && \
  apt-get install -y --no-install-recommends \
    libstdc++6 openssl libncurses5 locales ca-certificates curl gnupg git inotify-tools \
    \
  && apt-get clean && rm -f /var/lib/apt/lists/*_*

RUN sed -i 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen

# Install Node.js 20.x for frontend assets
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y --no-install-recommends nodejs && \
    apt-get clean && rm -f /var/lib/apt/lists/*_*


# Install hex + rebar
RUN mix local.hex --force && \
    mix local.rebar --force

# Set development ENV
ENV MIX_ENV="dev"


CMD mix deps.get && \
    cd assets && npm install && cd .. && \
    mix assets.setup && \
    mix assets.build && \
    mix ecto.setup && \
    mix phx.server