name: Elixir CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.16.2'
        otp-version: '26.2'

    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Restore _build cache
      uses: actions/cache@v3
      with:
        path: _build
        key: ${{ runner.os }}-build-elixir-1.16.2-otp-26.2-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-build-elixir-1.16.2-otp-26.2-

    - name: Install dependencies
      run: mix deps.get

    - name: Check formatting
      run: mix format --check-formatted

    - name: Run Credo
      run: mix credo --strict

    - name: Compile project
      run: mix compile --warnings-as-errors

    - name: Run tests
      run: mix test
      env:
        MIX_ENV: test
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/browsergrid_test
        REDIS_URL: redis://localhost:6379
